@startuml
title Classe conceptuel - Gestion des etudiants

skinparam classAttributeIconSize 0
skinparam shadowing false

class Etudiant {
  id
  nom
  prenom
  niveau
}

class Filiere {
  id
  nom
}

Filiere "1" -- "0..*" Etudiant : contient

@enduml
