@startuml
title Diagramme de sequence d'analyse - Ajouter un etudiant

actor "Utilisateur" as User
control "EtudiantServlet" as Servlet
entity "FiliereRepository" as FiliereRepo
entity "EtudiantRepository" as EtudiantRepo
database "MySQL\ndb_etudiants" as DB

User -> Servlet : POST /etudiants/add
activate Servlet

Servlet -> Servlet : Lire les donnees du formulaire
Servlet -> FiliereRepo : findById(filiereId)
FiliereRepo --> Servlet : Filiere

Servlet -> Servlet : Creer Etudiant
Servlet -> EtudiantRepo : save(etudiant)
EtudiantRepo -> DB : INSERT etudiant
EtudiantRepo --> Servlet : Etudiant

Servlet --> User : redirection /etudiants
deactivate Servlet

@enduml
